name: Auto Parser

on:
  schedule:
    - cron: '0 */1 * * *' # Запуск каждый час
  workflow_dispatch:      # Кнопка ручного запуска

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Обновлено до v4 (Node 20+)
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5 # Обновлено до v5 (Node 20+)
        with:
          python-version: '3.12'

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        run: python parser.py

      - name: Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add subscription.txt subscription_b64.txt
          git commit -m "Update configs: $(date)" || exit 0
          git push origin main
