name: Auto Parser

on:
  schedule:
    - cron: '0 */1 * * *' # Запуск каждый час
  workflow_dispatch:      # Кнопка для ручного запуска

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        run: python parser.py

      - name: Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Добавляем оба файла сразу
          git add subscription.txt subscription_b64.txt
          git commit -m "Update configs: $(date)" || exit 0
          git push
