name: Auto Parser

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        run: python parser.py

      - name: Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add subscription.txt subscription_b64.txt
          # Фикс: принудительно пушим, даже если гит капризничает
          git commit -m "Update configs: $(date)" || echo "No changes to commit"
          git push origin main --force
